buildscript {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        mavenCentral()
    }
    dependencies {
        classpath 'net.fabricmc:fabric-loom:1.9'
    }
}

apply plugin: 'net.fabricmc.fabric-loom'
apply plugin: 'maven-publish'

version = '7.45'
group = 'net.wurstclient'
base { archivesName = 'Wurst-Mace-Final' }

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://maven.fabricmc.net/' }
}

dependencies {
    minecraft 'com.mojang:minecraft:26.1'
    modImplementation 'net.fabricmc:fabric-loader:0.18.4'
    modImplementation 'net.fabricmc.fabric-api:fabric-api:0.104.0+26.1'
}
